---
# tasks/etcd_compaction.yml
# Compacts and defragments the etcd database

- name: Get etcd pod in namespace
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors:
      - app=etcd
  register: etcd_pods

- name: Fail if no etcd pods found
  ansible.builtin.fail:
    msg: "No etcd pods found in namespace {{ namespace }}"
  when: etcd_pods.resources | length == 0

- name: Execute etcdctl compact
  kubernetes.core.k8s_exec:
    namespace: "{{ namespace }}"
    pod: "{{ etcd_pods.resources[0].metadata.name }}"
    command: etcdctl compact $(etcdctl endpoint status --write-out=\"json\" | egrep -o '\"revision\":[0-9]*' | egrep -o '[0-9].*')
  register: compact_out

- name: Execute etcdctl defrag
  kubernetes.core.k8s_exec:
    namespace: "{{ namespace }}"
    pod: "{{ etcd_pods.resources[0].metadata.name }}"
    command: etcdctl defrag
  register: defrag_out

- name: Report compaction status
  ansible.builtin.debug:
    msg: "ETCD database compacted and defragmented successfully."
